const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const root = path.join(__dirname, '..');
const serverSource = fs.readFileSync(path.join(root, 'server.js'), 'utf8');
const buildSource = fs.readFileSync(path.join(root, 'scripts', 'build-netlify-dist.js'), 'utf8');
const envExample = fs.readFileSync(path.join(root, '.env.example'), 'utf8');
const indexHtml = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const appHtml = fs.readFileSync(path.join(root, 'app.html'), 'utf8');

assert.ok(serverSource.includes('if (require.main === module) {'), 'server must bind only as process entry point');
assert.ok(!serverSource.includes('\nstartWingmanServer();'), 'importing server.js must not unconditionally start a listener');
assert.ok(serverSource.includes('module.exports = { app, startWingmanServer, supabaseAdmin };'), 'server must export app and explicit starter');
assert.ok(!serverSource.includes("'unsafe-eval'"), 'Railway Helmet CSP must not allow unsafe-eval');
assert.ok(buildSource.includes('function cspFor(allowEval = false) {'), 'Netlify CSP must be generated by an explicit scoped policy helper');
assert.ok(buildSource.includes('const strictCsp = cspFor(false);'), 'Landing/legal Netlify CSP must use the eval-free policy');
assert.ok(buildSource.includes('const appCsp = cspFor(false);'), 'Netlify dashboard CSP must remain eval-free with the CSP-safe HEIC runtime');
assert.ok(!indexHtml.includes("'unsafe-eval'"), 'Landing-page meta CSP must remain eval-free');
assert.ok(!appHtml.includes("'unsafe-eval'") && appHtml.includes('vendor/heic2any-loader.js'), 'Dashboard must use the CSP-safe lazy HEIC loader');
assert.ok(envExample.includes('ALLOWED_ORIGINS="https://mywingman.pages.dev"'), 'production origin example must use only the verified Cloudflare Pages origin');
assert.ok(!envExample.includes('https://mywingman.com'), 'production origin example must not trust the misdirected mywingman.com host');
assert.ok(!envExample.includes('netlify.app'), 'production origin example must not advertise or trust retired Netlify origins');
assert.ok(!envExample.includes('https://*.pages.dev'), 'production origin example must not advertise wildcard preview origins');
assert.ok(serverSource.includes("const developmentCspDefaultSources = IS_PROD ? [] : ['http://localhost:*', 'ws://localhost:*'];"), 'Railway default CSP development sources must be development-only');
assert.ok(serverSource.includes('...developmentCspDefaultSources'), 'Railway default CSP must use the environment-scoped development sources');
assert.ok(serverSource.includes('...developmentCspConnectSources'), 'Railway connect CSP must use the environment-scoped development sources');
assert.ok(/script-src[^;\r\n]*https:\/\/static\.cloudflareinsights\.com(?=[\s;'"`]|$)/.test(buildSource), 'Cloudflare Pages Insights script must be allowed by the production artifact CSP');
assert.ok(/connect-src[^;\r\n]*https:\/\/cloudflareinsights\.com(?=[\s;'"`]|$)/.test(buildSource), 'Cloudflare Pages Insights reporting endpoint must be allowed by the production artifact CSP');
assert.ok(!/default-src[^;\r\n]*https:\/\/static\.cloudflareinsights\.com(?=[\s;'"`]|$)/.test(buildSource), 'Cloudflare Pages Insights must not broaden default-src');
assert.ok(/script-src[^;\r\n]*https:\/\/static\.cloudflareinsights\.com(?=[\s;'"`]|$)/.test(indexHtml) && /script-src[^;\r\n]*https:\/\/static\.cloudflareinsights\.com(?=[\s;'"`]|$)/.test(appHtml), 'source page CSPs must allow the Cloudflare Pages Insights script');
assert.ok(/connect-src[^;\r\n]*https:\/\/cloudflareinsights\.com(?=[\s;'"`]|$)/.test(indexHtml) && /connect-src[^;\r\n]*https:\/\/cloudflareinsights\.com(?=[\s;'"`]|$)/.test(appHtml), 'source page CSPs must allow the Cloudflare Pages Insights endpoint');

const output = execFileSync(process.execPath, ['-e', "require('./server'); process.stdout.write('IMPORT_OK')"], {
  cwd: root,
  encoding: 'utf8',
  timeout: 2500,
  env: {
    ...process.env,
    NODE_ENV: 'production',
    AICREDITS_API_KEY: 'test_key',
    AICREDITS_API_KEY_VISION: 'test_vision_key',
    SUPABASE_URL: 'https://example.supabase.co',
    SUPABASE_ANON_KEY: 'test_anon',
    SUPABASE_SERVICE_ROLE_KEY: 'test_service_role'
  }
});
assert.ok(output.endsWith('IMPORT_OK'), 'requiring server.js must return promptly');
assert.ok(!output.includes('Secure Wingman 3-Tier Backend Online'), 'requiring server.js must not open a listener');
console.log('✔ Runtime startup, CSP unsafe-eval, and production CORS example hardening passed.');
